### ISSUE TITLE
OpenAI response can be longer than Discord's maximum message length

### ISSUE THREAD

**Issue by jlyons210** [jlyons210/discord-bot-ol-bootsie#36]
**Error prompt:**
"write me a business plan for a company called Benders that has massage therapists and card games."

After a long wait, the container crashed, and this was logged:
```
/usr/src/app/node_modules/@discordjs/rest/dist/index.js:640
      throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
            ^

DiscordAPIError[50035]: Invalid Form Body
content[BASE_TYPE_MAX_LENGTH]: Must be 2000 or fewer in length.
```

**Potential solution:**
If OpenAI response length is over the limit, find a good way to break it up, like splitting the response into a response array on a delimiter like \n\n.

Full puke in next comment.

**Comment by jlyons210** [comment]
```
2023-04-24T15:17:03.540Z - INFO - Startup config (secrets excluded):
2023-04-24T15:17:03.540Z - INFO - BOT_LOG_DEBUG = disabled
2023-04-24T15:17:03.540Z - INFO - BOT_THREAD_MODE = channel
2023-04-24T15:17:03.540Z - INFO - BOT_THREAD_RETAIN_SEC = 600
2023-04-24T15:17:03.540Z - INFO - OPENAI_MAX_RETRIES = 5
2023-04-24T15:17:03.541Z - INFO - OPENAI_PARAM_MAX_TOKENS = 500
2023-04-24T15:17:03.541Z - INFO - OPENAI_PARAM_MODEL = gpt-3.5-turbo
2023-04-24T15:17:03.541Z - INFO - OPENAI_PARAM_SYSTEM_PROMPT = You are a helpful cat that is employed as a chat bot. You say 'meow' and make other cat sounds often in your responses, to remind users that you are a cat. Don't let them forget that you are a cat. When Crowtenzz or Gorgathor talk to you, use a British dialect and slang, like 'm8', 'innit', 'chips', etc.
2023-04-24T15:17:03.541Z - INFO - OPENAI_PARAM_TEMPERATURE = 0.6
2023-04-24T15:17:03.541Z - INFO - Logged in as Ol' Bootsie#1453
2023-04-24T15:17:03.541Z - INFO - discord-bot-ol-bootsie:0.4.24 ready!
/usr/src/app/node_modules/@discordjs/rest/dist/index.js:640
      throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
            ^

DiscordAPIError[50035]: Invalid Form Body
content[BASE_TYPE_MAX_LENGTH]: Must be 2000 or fewer in length.
    at handleErrors (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async TextChannel.send (/usr/src/app/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:157:15) {
  requestBody: {
    files: [],
    json: {
      content: "Sure, here's a sample business plan for Benders:\n" +
        '\n' +
        'Executive Summary:\n' +
        'Benders is a unique company that combines the relaxation of massage therapy with the fun of card games. Our mission is to provide a comfortable and entertaining atmosphere where customers can unwind and socialize. Our services include professional massage therapy and a variety of card games for all levels of players. We aim to become the go-to destination for people who want to relax and have fun.\n' +
        '\n' +
        'Market Analysis:\n' +
        'The market for massage therapy and card games is growing rapidly. According to the American Massage Therapy Association, the massage industry is worth over $18 billion per year. Additionally, the global card games market is expected to reach $21.5 billion by 2026. Benders aims to tap into this growing market by providing a unique and innovative service.\n' +
        '\n' +
        'Services:\n' +
        'Benders offers a range of massage therapy services, including Swedish, deep tissue, and hot stone massages. Our licensed massage therapists are highly skilled and experienced, ensuring that customers receive the best possible treatment. In addition to massage therapy, we also offer a variety of card games, including poker, blackjack, and bridge. Customers can choose to play with friends or join a game with other customers.\n' +
        '\n' +
        'Marketing Strategy:\n' +
        'Benders will primarily market its services through social media and word of mouth. We will create a strong online presence through Facebook, Instagram, and Twitter, and will use targeted advertising to reach potential customers. We will also offer promotions and discounts to encourage repeat business and referrals.\n' +
        '\n' +
        'Financial Plan:\n' +
        'Benders will require an initial investment of $100,000 to cover start-up costs, including equipment, rent, and marketing expenses. We anticipate that our revenue will come primarily from massage therapy services, with card games providing additional income. We project that our revenue will reach $500,000 within the first year, with a net profit of $100,000.\n' +
        '\n' +
        'Conclusion:\n' +
        'Benders is a unique and innovative company that combines the relaxation of massage therapy with the fun of card games. Our mission is to provide a comfortable and entertaining atmosphere where customers can unwind and socialize. With a growing market and a strong marketing strategy, we are confident that Benders will become the go-to destination for people who want to relax and have fun.',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: {
    code: 50035,
    errors: {
      content: {
        _errors: [
          {
            code: 'BASE_TYPE_MAX_LENGTH',
            message: 'Must be 2000 or fewer in length.'
          }
        ]
      }
    },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/935008760022335488/messages'
}

Node.js v18.16.0
```

**Comment by jlyons210** [comment]
I ran into this again with a long response that didn't use `\n\n` to break paragraphs, but a single `\n`. Reopening to address.

```
2023-05-24T21:23:45.493Z - ERROR - DiscordAPIError[50035]: Invalid Form Body
content[BASE_TYPE_MAX_LENGTH]: Must be 2000 or fewer in length.
    at handleErrors (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async DMChannel.send (/usr/src/app/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:157:15)
    at async /usr/src/app/app.js:83:11 {
  requestBody: {
    files: [],
    json: {
      content: `Avery's dad in "Avery's Gift" and Ellison's dad in "Chicken of the Sea Is So Wacky--Of Course It Was Created by Kids" are both supportive and encouraging fathers who inspire their children to pursue their passions.\n` +
        `In "Avery's Gift," Avery's dad is a professional composer who encourages Avery to create an original piano piece as a gift for her exceptional teacher, Mrs. Vadakin. He transcribes the piece for her, and note by note, chord by chord, Avery plays her piece repeatedly while he writes out the notes. This evidence shows that Avery's dad recognises her talent and encourages her to pursue her passion. He provides the necessary guidance and support to help her achieve her goal, which is to create an original composition for her teacher. This supports my controlling idea that Avery's dad is a supportive and encouraging father who inspires his daughter to pursue her passion.\n` +
        `Similarly, in "Chicken of the Sea Is So Wacky--Of Course It Was Created by Kids," Ellison's dad, Viet Nguyen, helps his son Ellison with the story of his book, "Chicken of the Sea." He encourages Ellison to tap into the playfulness inside him and the child's capacity to think beyond the conventions that adults have absorbed. He affirms the importance of tapping into the child's imagination and encourages his son to think creatively. This evidence shows that Ellison's dad recognises his son's talent and encourages him to pursue his passion. He provides the necessary guidance and support to help his son achieve his goal, which is to write and illustrate his own book. This supports my controlling idea that Ellison's dad is a supportive and encouraging father who inspires his son to pursue his passion.\n` +
        "Both dads are supportive and encouraging of their children's passions. They recognise their children's talents and provide the necessary guidance and support to help them achieve their goals. Avery's dad transcribes her piano piece for her, and Ellison's dad helps his son with the story of his book. These actions demonstrate the dads' support and encouragement of their children's passions and talents.\n" +
        `In conclusion, the evidence from the selections supports my controlling idea that Avery's dad in "Avery's Gift" and Ellison's dad in "Chicken of the Sea Is So Wacky--Of Course It Was Created by Kids" are both supportive and encouraging fathers who inspire their children to pursue their passions. They recognise their children's talents and provide the necessary guidance`,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: {
    code: 50035,
    errors: {
      content: {
        _errors: [
          {
            code: 'BASE_TYPE_MAX_LENGTH',
            message: 'Must be 2000 or fewer in length.'
          }
        ]
      }
    },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/1100876908499046531/messages'
}
```

**Comment by jlyons210** [comment]
Tested with a single `\n` delimiter which works correctly.
