### ISSUE TITLE
Check Discord intent permissions

### ISSUE THREAD

**Issue by jlyons210** [jlyons210/discord-bot-ol-bootsie#41]
Discord bots require certain permissions to be enabled for the bot to function, and the bot will ugly quit if the permissions aren't enabled in the Discord Developer Portal. I need to disable these permissions to see where the bot will raise errors, and exit with more helpful messages.

**Comment by jlyons210** [comment]
Not going to make code changes to trap this error, it's pretty self-explanatory. It only works for Gateway Intents. Channel permissions not being granted at bot invite time don't silently fail. I might revisit this, but it's not a huge priority.

```
/usr/src/app/node_modules/@discordjs/ws/dist/index.js:1066
        throw new Error("Used disallowed intents");
              ^

Error: Used disallowed intents
    at WebSocketShard.onClose (/usr/src/app/node_modules/@discordjs/ws/dist/index.js:1066:15)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/usr/src/app/node_modules/ws/lib/websocket.js:258:10)
    at TLSSocket.socketOnClose (/usr/src/app/node_modules/ws/lib/websocket.js:1264:15)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7)
```
