### ISSUE TITLE
429 API throttling errors should be retried

### ISSUE THREAD

**Issue by jlyons210** [jlyons210/discord-bot-ol-bootsie#52]
Code currently treats 5XX as retriable, and 4XX as fatal. Need to take a closer look at these, because a 429 API throttle causes the bot to quit with error.

It's amazing that I've made it this long without hitting an API throttle.

```
2023-05-10T23:30:38.030Z - INFO - discord-bot-ol-bootsie:0.7.0 ready!
2023-05-11T22:22:05.602Z - ERROR - An HTTP 429 (Too Many Requests) was returned. This indicates a bad request. Not retrying.
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: {
  error: {
    message: 'That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID eefa453c93f519cb311d7c7c6a17b0e9 in your message.)',
    type: 'server_error',
    param: null,
    code: null
  }
}
    at module.exports.requestChatCompletion (/usr/src/app/lib/lib-openai.js:112:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async probablyReactToMessage (/usr/src/app/app.js:180:25)
    at async Client.<anonymous> (/usr/src/app/app.js:111:7)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

Node.js v18.16.0
```

**Comment by jlyons210** [comment]
Re-opening due to a new bug introduced by gracefully handling a retriable error:

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at module.exports.requestChatCompletion (/usr/src/app/lib/lib-openai.js:122:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (/usr/src/app/app.js:63:32)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

This is caused by a fall-through:
Try `createChatCompletion`, `catch (error)` (when this happens) delay retry, fall-through to:
`if (responseText.trim() == '' && response.status == 200) {`  // responseText is undefined.

[lib-openai.js:120-134](https://github.com/jlyons210/discord-bot-ol-bootsie/blob/d2a81e024e2f226d8d855155c02b5dd471a76184/lib/lib-openai.js#L120) should be moved to within the `try` block, as it should only run when the OpenAI call succeeds.
